### ISSUE TITLE
Not working in 9.0.2

### ISSUE THREAD

**Issue by shrekin** [fubaWoW/WIM_ElvUI_Skin#3]
It completly doesn't use ElvUI window style on the latest update 9.0.2. 
Could it be fixed?

**Comment by crborga** [comment]
Working fine for me. Maybe you need to select it again the skins.

**Comment by Isselbaecher** [comment]
Also not working for me. 
I select the skin - nothing happens.
I reload - nothing happens.
I check the config - the skin is still selected.

**Comment by fubaWoW** [comment]
Im actually not playing wow but some comments on Curseforge say it do work in Classic as well as in Retail.
As of there is no error message i can not figure out what is going wrong :/

**Comment by crborga** [comment]
Enable scripterrors to see lua errors if they are disabled. It will help to determine what needs to be fixed.

**Comment by fubaWoW** [comment]
Tested in 10.0 now and it is still working without any errors!

it also switches the skin "on the fly" when chance all available skins.
maybe some of your addons break something?
anyway...
you don't provided any LUA-Error so cant do anything.
