### ISSUE TITLE
Enlarge button?

### ISSUE THREAD

**Issue by AmenitradieDruidin** [fubaWoW/WIM_ElvUI_Skin#4]
Hello, is there a way to enlarge the buttons on the side? They are really very small with me. Unfortunately, it makes it difficult to use the functions. 

![Screenshot 2020-11-g27 135443](https://user-images.githubusercontent.com/39033070/100451730-323e6e00-30b8-11eb-9342-931a811bc8d9.jpg)

**Comment by fubaWoW** [comment]
uhu...
it IS possible but you need to chance it manually for EACH icon in the ``skin.lua`` file.
BUT this will also "stretch" the icon(s) and this will maybe look ugly!

You need to change ``width = 16`` and ``height = 16`` to example ``width = 32`` and ``height= 32`` for the icons you need.
All the Icons you need to change are in the section ``widgets`` in the file ``skin.lua``

But as of the Icons are just 16x16 it is nor recommended at all!
