### ISSUE TITLE
Packaging for Alternate Providers (WowUp/Ajour)

### ISSUE THREAD

**Issue by Scryrz** [fubaWoW/WIM_ElvUI_Skin#6]
Now that Curseforge has revoked API access from third-party addon managers like WowUp and Ajour, are there currently any plans to host this addon elsewhere (Wago, WowInterface)? If not, would you be open to using BigWigs Packager to append formatted zips so that the aforementioned third-party addon clients can install directly from this repo?

[BigWigs Packager Action](https://github.com/BigWigsMods/packager)

**Comment by WybeBosch** [comment]
Would love to see this aswell!

**Comment by fubaWoW** [comment]
well...
as im actually not playing wow on any version it's hard for me to test alle the new Addon pages.
I know the Curseforge Api is kinda "s*it" but right now this is my only delivery platform.

Maybe i will play Dragonflight and if i do so i'm pretty sure i will also release on the new Addon-Pages!

**Comment by WybeBosch** [comment]
Understandable! Hope you checkout dragonflight and that you enjoy it, but also understand if not :)

**Comment by jpd-oliveira** [comment]
Can you just have a release in github so we can use wowup?

**Comment by fubaWoW** [comment]
Done.
updating my addons to use the [BigWigs Packager Action](https://github.com/BigWigsMods/packager) what is REALLY nice!
thanks @Scryrz for the tip!
